general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

# Completely transparent background
background {
    monitor =
    path = screenshot # Captures current desktop for the blur effect
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.9696
}

# Centered input box
input-field {
    monitor =
    font_family = Monospace
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(22, 169, 160, 1.0)
    inner_color = rgba(20, 20, 20, 0.8)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <i>place thy passphrase in thy holy place...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

# Clock display
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 0.9)
    font_size = 64
    font_family = AtkinsonHyperlegible Mono NF
    position = 0, 80
    halign = center
    valign = center
}
